include:
  - component: $CI_SERVER_FQDN/gitlab-pipelines/generic-dockerfile/generic@1
    inputs:
      master-tag: latest
  - component: $CI_SERVER_FQDN/gitlab-pipelines/generic-dockerfile/only-tags@1
    inputs:
      build-args: "VERSION=${CI_COMMIT_TAG}-alpine"
